name: TNEB Singanallur Check

on:
  schedule:
    # 4:00 PM IST
    - cron: '30 10 * * *'
    
    # 4:10 PM IST
    - cron: '40 10 * * *'
    
    # 4:20 PM IST
    - cron: '50 10 * * *'

  workflow_dispatch: # This adds a magic "Run manually" button so you can test it anytime!

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Set up Python Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Project Dependencies
      run: |
        pip install -r requirements.txt

    - name: Execute Captcha Bypass Scraper
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python scraper.py
